= Textantworten für Concurrency 2 Übung
Joël Plambeck <plambjoe@students.zhaw.ch>
:icons: font

== 2.3 Thread-Safe Circular Buffer
NotifyAll() wird verwendet, da es unter Umständen sein kann, dass getAuftraege und putAuftraege im
Warteraum sind. Wenn dann ein notify() kommt, kann es sein, dass ein Auftrag geweckt wird der noch nicht
weitermachen darf, da die Bedingung immernoch so ist, dass er warten muss.
Dies ist bei kleinem Buffer mit grosser Anzahl Producer & Consumer gut möglich.

== 3.2 The dining philosophers

=== a)
Wenn man die Zeit (= timeout) zwischen dem Greifen der ersten Gabel und dem greifen der zweiten Gabel nimmt.

=== c)
Man könnte einen Philosopher 'trainieren', dass er zuerst die rechte anstatt die linke greift.
Somit könnte die Kette unterbrochen werden.

== 4.2 Mandelbrot

==== a)
Mit 16 Threads geht es am schnellsten (icon:apple[] MBP Quad-Core)

==== b)
Da mein Computer ein Quad-core prozessor hat, sind die versionen mit `Anzahl Threads % 4 = 0` schneller als ein Thread mehr.

=== 4.2.1
SingleThreadPool:: Macht keint Sinn, da mehrere Threads verwendet werden sollen.
FixedThreadPool::
Wäre möglich, die Höhe könnte als maximale Anzahl Threads verwendet werden.
CachedThreadPool:: Wäre möglich, sehr unwahrscheinlich, dass die Berechnung länger als 60s braucht.
WorkStealingPool:: Wäre möglich, könnte auf verschiedenen Geräten performant laufen, da es die Anzahl Kerne in Betracht zieht.

.Messungen:
|===
| | FixedThreadPool | CachedThreadPool | WorkStealingPool
| 3 Threads | 2517ms | 4541ms | 2594ms
| 10 Threads | 1113ms | 1099ms | 1115ms
| 16 Threads | 1108ms | 1123ms | 1108ms
|===

Wie in den Messungen ersichtlich, ist die FixedThreadPool methode am schnellsten.
Dies stellt zugleich sicher, dass nicht mehr Threads als die Höhe des Bildes erstellt werden.

